# Generated by Django 6.0.5 on 2026-05-28 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='반려쓰레기 이름')),
                ('story', models.TextField(verbose_name='해방일지')),
                ('image', models.ImageField(upload_to='contents/%Y/%m/', verbose_name='사진')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('password_hash', models.CharField(max_length=256, verbose_name='수정용 비밀번호')),
                ('category', models.CharField(choices=[('immediate_trash', '즉시해방 — 직접 버리기'), ('immediate_exhibition', '즉시해방 — 실물전시 참여'), ('temporary_storage', '임시보관')], max_length=30, verbose_name='카테고리')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '거절됨')], default='pending', max_length=20, verbose_name='승인 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to=settings.AUTH_USER_MODEL, verbose_name='작성자 계정')),
            ],
            options={
                'verbose_name': '해방일지',
                'verbose_name_plural': '해방일지 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='댓글')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contents.content')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글 목록',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('empathy', '공감'), ('sad', '슬픔'), ('angry', '화남')], max_length=20)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='contents.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '반응',
                'verbose_name_plural': '반응 목록',
                'unique_together': {('content', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('throw', '버려라'), ('keep', '아직은 말아라')], max_length=20)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='contents.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '투표',
                'verbose_name_plural': '투표 목록',
                'unique_together': {('content', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='contents.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '찜',
                'verbose_name_plural': '찜 목록',
                'unique_together': {('content', 'user')},
            },
        ),
    ]
