# Generated by Django 6.0.5 on 2026-05-28 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='알림 이메일 (선택)'),
        ),
        migrations.AddField(
            model_name='content',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='상단 노출 만료 시각'),
        ),
        migrations.AddField(
            model_name='vote',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('jury_summon', '배심원 소환권'), ('judge_hammer', '대법관의 망치')], max_length=30)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_by', to='contents.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '상점 구매 내역',
                'verbose_name_plural': '상점 구매 내역 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
