# Generated by Django 6.0.5 on 2026-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_author_email_content_featured_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_approval', models.BooleanField(default=True, verbose_name='콘텐츠 업로드 시 관리자 승인 필요')),
                ('auto_approve_groups', models.CharField(blank=True, help_text='이 그룹에 속한 회원은 승인 없이 바로 공개됩니다. 예: 1기참여자, 운영팀', max_length=500, verbose_name='자동 승인 그룹 (쉼표로 구분)')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
    ]
