# Generated by Django 6.0.5 on 2026-05-29 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_siteconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guest_nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='비회원 닉네임'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='archive_comment_public',
            field=models.BooleanField(default=False, verbose_name='댓글'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='archive_reaction_public',
            field=models.BooleanField(default=False, verbose_name='반응'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='archive_read_public',
            field=models.BooleanField(default=False, verbose_name='읽기'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='exhibition_comment_public',
            field=models.BooleanField(default=False, verbose_name='댓글'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='exhibition_reaction_public',
            field=models.BooleanField(default=False, verbose_name='반응'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='exhibition_read_public',
            field=models.BooleanField(default=False, verbose_name='읽기'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='exhibition_wishlist_public',
            field=models.BooleanField(default=False, verbose_name='찜'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='temporary_comment_public',
            field=models.BooleanField(default=False, verbose_name='댓글'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='temporary_reaction_public',
            field=models.BooleanField(default=False, verbose_name='반응'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='temporary_read_public',
            field=models.BooleanField(default=False, verbose_name='읽기'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='write_public',
            field=models.BooleanField(default=False, verbose_name='비회원 글쓰기 허용'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
