# Generated by Django 6.0.5 on 2026-05-28 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='회원코드')),
                ('group_name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '프로젝트 코드',
                'verbose_name_plural': '프로젝트 코드 목록',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='project_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='프로젝트 그룹'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='누적 포인트 (레벨 기준)'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='action',
            field=models.CharField(choices=[('register', '회원가입'), ('upload', '콘텐츠 업로드'), ('comment', '댓글 작성'), ('reaction', '반응 남기기'), ('wishlist', '찜하기'), ('vote', '투표하기'), ('spend', '포인트 사용')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('regular', '일반 회원'), ('project', '프로젝트 참여회원')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='사용 가능 포인트'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
